[build]
  publish = "build"

[[redirects]]
 from = "/public/api/core/*"
 to = "/api/core/"

[[redirects]]
 from = "/public/api/react/*"
 to = "/api/react/"

[[redirects]]
 from = "/public/api/material/*"
 to = "/api/material/"

[[redirects]]
 from = "/public/api/vanilla/*"
 to = "/api/vanilla/"

[[redirects]]
 from = "/public/api/angular/*"
 to = "/api/angular/"

[[redirects]]
 from = "/public/api/vue/*"
 to = "/api/vue/"

[[redirects]]
 from = "/public/api/vue2/*"
 to = "/api/vue2/"

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'sha256-O8zYuOjyuzUZDv3fub7DKfAs5TEd1dG+fz+hCSCFmQA=' 'sha256-nlA5Eh6znySQnjHmn8Yf6Vfz2I3XgXggeuOKoXBiBC0=' static.cloudflareinsights.com cloudflareinsights.com/cdn-cgi/rum; connect-src 'self' cloudflareinsights.com/cdn-cgi/rum; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'none'; frame-ancestors 'self';"
      X-Frame-Options = "SAMEORIGIN"
      X-Content-Type-Options = "nosniff"
      Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
